### ISSUE TITLE
get PostGIS working, added lat/long coords to `sc.langauges` and update wiki with instructions on using PostGIS locally

### ISSUE THREAD

**Issue by michaelmarshall** [CordField/cordtables#122]

**Comment by questionreality** [comment]
resources:
https://www.youtube.com/watch?v=hMn74o11wdk
https://postgis.net/

**Comment by questionreality** [comment]
all we need is to store the data as geospatial data 
can later do visualizations

**Comment by questionreality** [comment]
https://stackoverflow.com/a/65293118/13888168 
steps to install postgis on docker container. 
`&& apt-get install postgresql-12-postgis-3 -y \`  -> this line needs to be 
`&& apt-get install postgresql-14-postgis-3 -y \` as we are using postgres v14

**Comment by questionreality** [comment]
list & read:
- [ ] need to remove the query abstraction in order to return geography datatype in a human readable format

create & update:
- [ ] need to figure out a way to conveniently update/create the value
