### ISSUE TITLE
postgis visualization

### ISSUE THREAD

**Issue by michaelmarshall** [CordField/cordtables#165]

**Comment by questionreality** [comment]
another column for visualization. 
clicking on it could result in a popup/modal or redirect you to a new page

**Comment by questionreality** [comment]
need to figure out srid from latitude and longitude (refer languages.update.kt file)

**Comment by questionreality** [comment]
https://developers.google.com/maps/documentation/javascript/overview 
google maps api

**Comment by questionreality** [comment]
- [ ] get back data in geojson format
- [ ] create mapbox div
- [ ] figure out a way to pass geojson data when hovering over a row
