### ISSUE TITLE
update secure list query abstraction for postGIS

### ISSUE THREAD

**Issue by michaelmarshall** [CordField/cordtables#190]
the `sc.languages` `Read` and `List` files had to have their queries "hand written" because the utility function wasn't ready for the new `coordinates` column. 

Update the abstraction (somehow) to handle it and then update the files to call the utility function.

**Comment by questionreality** [comment]
two possible options: 
1. function takes in additional parameter that is the SQL string for columns which don't fit the abstraction. 
2. the columnName parameter is split into 2 parameters (the column that is used in the case when condition and the column that is returned)
