### ISSUE TITLE
Generic Auto Complete Endpoint and Widget

### ISSUE THREAD

**Issue by michaelmarshall** [CordField/cordtables#302]
Create an endpoint that accepts a table name, column name, quantity, and search string and returns the top [quantity] responses from that table by searching the column for the search string. The only data returned will be the `id` of the row and the full string from the column being searched.

Then create a generic widget on the FE to implement an autocomplete input box and selection list.

Then use that widget on the `sc-global-partner-assessments` table in the create form for the `Partner` field. This field will actually query the `common.organizations` table and the `name` column.

**Comment by questionreality** [comment]
load the page first, then make requests asynchronously to replace uuids with the actual data (names)

**Comment by questionreality** [comment]
add new field to columnDescription for result column name
