### ISSUE TITLE
BUG: fix swagger in `dev`

### ISSUE THREAD

**Issue by michaelmarshall** [CordField/cordtables#348]
the latest build wasn't deploying correct in `dev` because of a bug that looked like a swagger config thing. something recent may have conflicted with swagger. uncomment the lines in the application.yml file and watch ECS container's logs to get a read on the error(s).

![image](https://user-images.githubusercontent.com/1165460/147988364-d3f42b74-b186-4434-b237-4bfa28dcdacb.png)

**Comment by Rhuan288souza** [comment]
@daniel-leod, could you please describe what was the solution for this bug?

**Comment by daniel-leod** [comment]
@Rhuan288souza The solution was to remove an [extra indentation](https://github.com/CordField/cordtables/pull/359/commits/0fb859a0e6d278863ba394d61d795fd5dab3e9b4#diff-0aeeafa48bf1de21c75ac5a3d4f82992b3d66bdc0b7dda14eecf54b55bb73f24L44) on the `infra/dev/cf-server/application.yml` file.
